REQ_NONE = 0
REQ_LOGIN = 1
REQ_LOGOFF = 2

REQ_PING = 3

REQ_ENTER_ROOM = 4
REQ_LEAVE_ROOM = 5
REQ_ENTER_GUILD = 6
REQ_LEAVE_GUILD = 7
REQ_KICK = 8
REQ_ADD_FREIEND = 9
REQ_DEL_FREIEND = 10
REQ_GUILD_JOIN = 11
REQ_GUILD_KICk = 12
REQ_GUILD_DEL = 13
REQ_ROOM_MSG = 14

REQ_KICK = 99
REQ_SUB_CHNANNEL = 100
REQ_UNSUB_CHANNEL = 101
REQ_SUB_WORLD = 102
